apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-bf2-dpu
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/default/bluefield
          contents:
            source: "data:,BF_MODE%3dnic%0A"
          user:
            name: root
          group:
            name: root
          mode: 0644
    systemd:
      units:
        - name: rshim.service
          enabled: false
          contents: |
            [Unit]
            Description=Podman container-rshim.service
            Documentation=man:podman-generate-systemd(1)
            Wants=network.target
            After=network-online.target
            RequiresMountsFor=%t/containers

            [Service]
            Environment=PODMAN_SYSTEMD_UNIT=%n
            EnvironmentFile=-/etc/default/bluefield
            Restart=on-failure
            TimeoutStopSec=70
            ExecStartPre=/bin/rm -f %t/container-rshim.pid %t/container-rshim.ctr-id
            ExecStart=/bin/bash -c '/usr/bin/podman run --conmon-pidfile %t/container-rshim.pid --cidfile %t/container-rshim.ctr-id --cgroups=no-conmon --pull always --replace --rm --name rshim --privileged --volume /dev:/dev --volume /lib/modules/$$(uname -r):/lib/modules/$$(uname -r) --entrypoint rshim -dit quay.io/kwozyman/toolbox:bluefield -f -l 3'
            ExecStop=/usr/bin/podman stop --ignore --cidfile %t/container-rshim.ctr-id -t 10
            ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %t/container-rshim.ctr-id
            PIDFile=%t/container-rshim.pid
            Type=forking

            [Install]
            WantedBy=multi-user.target default.target
        - name: dpu-switch.service
          enabled: false
          contents: |
            [Unit]
            Description=Switch BlueField2 card to SmartNIC/DPU mode
            RequiresMountsFor=%t/containers
            Requires=rshim
            Before=kubelet

            [Service]
            SuccessExitStatus=0 120
            RemainAfterExit=True
            Environment=PODMAN_SYSTEMD_UNIT=%n
            EnvironmentFile=-/etc/default/bluefield
            ExecStart=/bin/bash -c '/usr/bin/podman run --pull always --replace --rm --name bf-switch --privileged --volume /dev:/dev --env BF_MODE --entrypoint /usr/local/bin/bf-switch quay.io/kwozyman/toolbox:bluefield && shutdown -r now'
            Type=oneshot

            [Install]
            WantedBy=multi-user.target default.target
