apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 
  labels:
    machineconfiguration.openshift.io/role: 
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: 
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/NetworkManager/conf.d/disablenic.conf
